package net.backend.journalApp.model;

import lombok.*;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Document(collection="journals") // Marks this class as a MongoDB document, specifying that it will be mapped to the "journals" collection.
@Data   // Lombok annotation that automatically generates getters, setters, toString, equals, and hashCode methods.
@NoArgsConstructor  // Lombok annotation that generates a no-argument constructor for the class.
public class JournalModel {

    @Id
    private ObjectId id;  // The unique identifier for each journal entry, automatically generated by MongoDB.

    @NonNull
    private String title; // The title of the journal entry. The @NonNull annotation ensures this field cannot be null.

    private String content; // The content of the journal entry. It is optional and can be left empty.

    @CreatedDate // Automatically sets the value of createdAt to the timestamp when the document is first saved to MongoDB.
    private LocalDateTime createdAt; // The timestamp indicating when the journal entry was created.

    @LastModifiedDate // Automatically updates the value of updatedAt to the current timestamp whenever the document is modified.
    private LocalDateTime updatedAt; // The timestamp indicating when the journal entry was last updated.
}
